### ISSUE TITLE
Password change

### ISSUE THREAD

**Issue by burjulius** [parking-lots/parking-rest-api#36]
New API doesn't check old password when changing a password. For instance, as a user, I can type any old password and password will be changed.

**Comment by LinaPo** [comment]
Thanks for noticing. Since user doesn't have to provide old password, old password is redundant in the request. As a result, we are changing new REST api:
now the change password request should look like this:
{"newPassword":"pass2"}

Please, change the request accordingly in the front-end.

**Comment by LinaPo** [comment]
Changes made in back-end
